### ISSUE TITLE
Event Instances attributes not showing

### ISSUE THREAD

**Issue by mattaellis** [pixelpudu/wpspx#1]
We have several Event Instances set up within Spetrix. (Eg: 'Event Description' with 4 items).

Looking through the plugin, it seems that these attributes should display within `table-rows.php`.

```
<?php $perfattri = $performance->attributes; if ($perfattri): ?>
<tr class="<?php echo $tr_class; ?> attributes">
  <td colspan="2" style="border-top:none; padding: 0;">
    <?php format_performances_attributes($performance->attributes); ?>
  </td>
</tr>
```

The Event Instances attributes are being set in the `instances_event_id_XXXX.txt` file.
```
<Instance id="63403">
<Attribute>
    <Name>Event Description Attributes</Name>
    <Value>SIGNED PERFORMANCE</Value>
</Attribute>
```

But they are not being displayed.

How can I get Event Instances attributes to display on the front-end please?

**Comment by martingreenwood** [comment]
@honchodesign Have you got any errors in your debug log file or are they just plain refusing to show? You may also want to check your spektrix back office to make sure they are visible to the web.

**Comment by mattaellis** [comment]
No, there are no errors in the debug log. 

In Spektrix, the attributes are set to 'Public'. Done via Settings > Attribute Templates > Event Instances > 'Event status Attributes' ( ✓ Public).

Is that where you mean to be 'visible to the web', or is there a setting I've missed?

**Comment by martingreenwood** [comment]
The issue here was the attribute setup in Spektrix Back Office -  attributes need to be setup as checkboxes rather than dropdown / select boxes
